service: serverless-slack-bot
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_NAME: ${env:DB_NAME}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}

functions:
  message-event:
    handler: src/functions/bot/message-event.handler
    events:
      - http:
          path: slack/events
          method: post
  message-sender:
    handler: src/functions/bot/message-sender.handler
    events:
      - http:
          path: slack/messages
          method: post
  get-applications:
    handler: src/functions/apps-registry/get-all-applications.handler
    events:
      - http:
          path: applications
          method: get
  register-application:
    handler: src/functions/apps-registry/register-application.handler
    events:
      - http:
          path: applications
          method: post
