service: slackbot
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  logRetentionInDays: 30
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_NAME: ${env:DB_NAME}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    WELCOME_MESSAGE_DELAY_DAYS: ${env:WELCOME_MESSAGE_DELAY_DAYS}
    WELCOME_MESSAGE_DELAY_HOURS: ${env:WELCOME_MESSAGE_DELAY_HOURS}
    WELCOME_MESSAGE_DELAY_MINUTES: ${env:WELCOME_MESSAGE_DELAY_MINUTES}
  apiGateway:
    apiKeys:
      - value: ${env:CONVERSATION_BUILDER_API_KEY}
        description: Api key for conversation builder app
        customerId: conversation-builder
      - value: ${env:JOKE_SENDER_API_KEY}
        description: Api key for joke sender app
        customerId: joke-sender

plugins:
  - serverless-offline

functions:
  handle-events:
    handler: src/functions/slack-api/handle-events.handler
    events:
      - http:
          path: slack/events
          method: post
          private: false

  send-message:
    handler: src/functions/slack-api/send-message.handler
    events:
      - http:
          path: slack/messages
          method: post
          private: true

  broadcast-message:
    handler: src/functions/slack-api/broadcast-message.handler
    timeout: 30
    events:
      - http:
          path: slack/broadcast-message
          method: post
          private: true

  get-users:
    handler: src/functions/slack-api/get-users.handler
    events:
      - http:
          path: slack/users
          method: get
          private: true

  create-converstaions:
    handler: src/functions/slack-api/create-conversation.handler
    events:
      - http:
          path: slack/conversations
          method: post
          private: true

  get-applications:
    handler: src/functions/apps-registry/get-all-applications.handler
    events:
      - http:
          path: applications
          method: get
          private: true

  register-application:
    handler: src/functions/apps-registry/register-application.handler
    events:
      - http:
          path: applications
          method: post
          private: true
