-- Revoke privileges from 'public' role
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON DATABASE "postgres" FROM PUBLIC;

-- Read-only role
CREATE ROLE readonly;
GRANT CONNECT ON DATABASE "postgres" TO readonly;
GRANT USAGE ON SCHEMA slack_bot TO readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA slack_bot TO readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA slack_bot GRANT SELECT ON TABLES TO readonly;

-- Read/write role
CREATE ROLE readwrite;
GRANT CONNECT ON DATABASE "postgres" TO readwrite;
GRANT USAGE ON SCHEMA slack_bot TO readwrite;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA slack_bot TO readwrite;
ALTER DEFAULT PRIVILEGES IN SCHEMA slack_bot GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO readwrite;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA slack_bot TO readwrite;
ALTER DEFAULT PRIVILEGES IN SCHEMA slack_bot GRANT USAGE ON SEQUENCES TO readwrite;